name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  BuildRelease:
    if: github.repository_owner == 'MovTery' && !startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      MOVTERY_KEYSTORE_PASSWORD: ${{ secrets.MOVTERY_KEYSTORE_PASSWORD }}
      MY_API_TOKEN: ${{ secrets.MY_API_TOKEN }}
      MY_PRIVATE_API_TOKEN: ${{ secrets.MY_PRIVATE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JRE JAR files
        run: |
          chmod +x gradlew
          mkdir out
          ./gradlew jre_lwjgl3glfw:build --no-daemon

      - name: Build Release ${{matrix.arch}}
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assemblerelease -Darch=${{matrix.arch}}

      - name: Upload Release ${{matrix.arch}}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ZalithLauncher(Release) ${{matrix.arch}}
          path: ZalithLauncher/build/outputs/apk/release/*

  BuildDebug:
    if: github.repository_owner != 'MovTery' || startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JRE JAR files
        run: |
          chmod +x gradlew
          mkdir out
          ./gradlew jre_lwjgl3glfw:build --no-daemon

      - name: Build Debug ${{matrix.arch}}
        if: github.ref_name != 'main'
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug ${{matrix.arch}}
        if: github.ref_name != 'main'
        uses: actions/upload-artifact@v4
        with:
          name: ZalithLauncher(Debug) ${{matrix.arch}}
          path: ZalithLauncher/build/outputs/apk/debug/*